# Site settings
title: VeriDrone
email: 
description: > # this means to ignore newlines until "baseurl:"
    This project investigates the application of a technique called
    Foundational Verification to cyber-physical systems, paving the way to reaching
    previously unattainable levels of safety for cyber-physical
    systems. To make sure that the techniques in this project are
    practical, we evaluate them within the context of a real
    flying quadcopter.
baseurl: "/veridrone" # the subpath of your site, e.g. /blog/
url: "http://ucsd-pl.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:
logo: veridrone-logo-grey.png
cse-logo: CSELogo_4Cv.jpg
both-logos: veridrone-cse.png
ucsd-logo: ucsd.png

# Authors
authors:
  daricket:
    image-url: /images/dan-head.jpg
    name: Dan Ricketts
    webpage: http://cseweb.ucsd.edu/~daricket/
  lerner:
    image-url: /images/sorin-head.jpg
    name: Sorin Lerner
    webpage: http://cseweb.ucsd.edu/~lerner/

# Build settings
markdown: kramdown
