exception Error

type token = 
  | XOR_ASSIGN of (Cabs.cabsloc)
  | WHILE of (Cabs.cabsloc)
  | VOLATILE of (Cabs.cabsloc)
  | VOID of (Cabs.cabsloc)
  | VAR_NAME of (string * Pre_parser_aux.identifier_type ref * Cabs.cabsloc)
  | UNSIGNED of (Cabs.cabsloc)
  | UNION of (Cabs.cabsloc)
  | UNDERSCORE_BOOL of (Cabs.cabsloc)
  | TYPEDEF_NAME of (string * Pre_parser_aux.identifier_type ref * Cabs.cabsloc)
  | TYPEDEF of (Cabs.cabsloc)
  | TILDE of (Cabs.cabsloc)
  | SWITCH of (Cabs.cabsloc)
  | SUB_ASSIGN of (Cabs.cabsloc)
  | STRUCT of (Cabs.cabsloc)
  | STRING_LITERAL of (bool * int64 list * Cabs.cabsloc)
  | STATIC of (Cabs.cabsloc)
  | STAR of (Cabs.cabsloc)
  | SLASH of (Cabs.cabsloc)
  | SIZEOF of (Cabs.cabsloc)
  | SIGNED of (Cabs.cabsloc)
  | SHORT of (Cabs.cabsloc)
  | SEMICOLON of (Cabs.cabsloc)
  | RPAREN of (Cabs.cabsloc)
  | RIGHT_ASSIGN of (Cabs.cabsloc)
  | RIGHT of (Cabs.cabsloc)
  | RETURN of (Cabs.cabsloc)
  | RESTRICT of (Cabs.cabsloc)
  | REGISTER of (Cabs.cabsloc)
  | RBRACK of (Cabs.cabsloc)
  | RBRACE of (Cabs.cabsloc)
  | QUESTION of (Cabs.cabsloc)
  | PTR of (Cabs.cabsloc)
  | PRAGMA of (string * Cabs.cabsloc)
  | PLUS of (Cabs.cabsloc)
  | PERCENT of (Cabs.cabsloc)
  | PACKED of (Cabs.cabsloc)
  | OR_ASSIGN of (Cabs.cabsloc)
  | NEQ of (Cabs.cabsloc)
  | MUL_ASSIGN of (Cabs.cabsloc)
  | MOD_ASSIGN of (Cabs.cabsloc)
  | MINUS of (Cabs.cabsloc)
  | LT of (Cabs.cabsloc)
  | LPAREN of (Cabs.cabsloc)
  | LONG of (Cabs.cabsloc)
  | LEQ of (Cabs.cabsloc)
  | LEFT_ASSIGN of (Cabs.cabsloc)
  | LEFT of (Cabs.cabsloc)
  | LBRACK of (Cabs.cabsloc)
  | LBRACE of (Cabs.cabsloc)
  | INT of (Cabs.cabsloc)
  | INLINE of (Cabs.cabsloc)
  | INC of (Cabs.cabsloc)
  | IF of (Cabs.cabsloc)
  | HAT of (Cabs.cabsloc)
  | GT of (Cabs.cabsloc)
  | GOTO of (Cabs.cabsloc)
  | GEQ of (Cabs.cabsloc)
  | FOR of (Cabs.cabsloc)
  | FLOAT of (Cabs.cabsloc)
  | EXTERN of (Cabs.cabsloc)
  | EQEQ of (Cabs.cabsloc)
  | EQ of (Cabs.cabsloc)
  | EOF
  | ENUM of (Cabs.cabsloc)
  | ELSE of (Cabs.cabsloc)
  | ELLIPSIS of (Cabs.cabsloc)
  | DOUBLE of (Cabs.cabsloc)
  | DOT of (Cabs.cabsloc)
  | DO of (Cabs.cabsloc)
  | DIV_ASSIGN of (Cabs.cabsloc)
  | DEFAULT of (Cabs.cabsloc)
  | DEC of (Cabs.cabsloc)
  | CONTINUE of (Cabs.cabsloc)
  | CONSTANT of (Cabs.constant * Cabs.cabsloc)
  | CONST of (Cabs.cabsloc)
  | COMMA of (Cabs.cabsloc)
  | COLON of (Cabs.cabsloc)
  | CHAR of (Cabs.cabsloc)
  | CASE of (Cabs.cabsloc)
  | BUILTIN_VA_ARG of (Cabs.cabsloc)
  | BREAK of (Cabs.cabsloc)
  | BARBAR of (Cabs.cabsloc)
  | BAR of (Cabs.cabsloc)
  | BANG of (Cabs.cabsloc)
  | AUTO of (Cabs.cabsloc)
  | ATTRIBUTE of (Cabs.cabsloc)
  | ASM of (Cabs.cabsloc)
  | AND_ASSIGN of (Cabs.cabsloc)
  | ANDAND of (Cabs.cabsloc)
  | AND of (Cabs.cabsloc)
  | ALIGNOF of (Cabs.cabsloc)
  | ALIGNAS of (Cabs.cabsloc)
  | ADD_ASSIGN of (Cabs.cabsloc)


val translation_unit_file: (Lexing.lexbuf -> token) -> Lexing.lexbuf -> (unit)