#!/bin/sh
# File generated by ocamlbuild

cd /home/mario/LocalCode/quadcopter/compile/compcert-2.4

rm -f runtime/i64_dtos.o
rm -f runtime/i64_dtou.o
rm -f runtime/i64_sar.o
rm -f runtime/i64_sdiv.o
rm -f runtime/i64_shl.o
rm -f runtime/i64_shr.o
rm -f runtime/i64_smod.o
rm -f runtime/i64_stod.o
rm -f runtime/i64_stof.o
rm -f runtime/i64_udiv.o
rm -f runtime/i64_udivmod.o
rm -f runtime/i64_umod.o
rm -f runtime/i64_utod.o
rm -f runtime/i64_utof.o
rm -f runtime/libcompcert.a
rm -f runtime/vararg.o
rm -f tools/ndfun.cmi
rm -f tools/ndfun.cmx
rm -f tools/ndfun.o
# Also clean the script itself
rm -f /home/mario/LocalCode/quadcopter/compile/compcert-2.4/_build/sanitize.sh
